const conflictingReasons = {
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  VIEW_ONLY_SESSION: "VIEW_ONLY_SESSION",
  NO_EDITING_RIGHTS: "NO_EDITING_RIGHTS",
  VERSIONS_CONFLICTED: "VERSIONS_CONFLICTED",
  FILE_IS_SAVE_PENDING: "FILE_IS_SAVE_PENDING",
  UNSHARED_OR_DELETED: "UNSHARED_OR_DELETED"
};
export default conflictingReasons;
