package com.graebert.storage.Entities;

public enum KudoErrorCodes {
  FILE_SESSION_EXPIRED("KF0"),
  EXISTING_EDITING_SESSION("KF1"),
  UNABLE_TO_CHECKOUT_FILE("KF2"),
  UNABLE_TO_CHECKIN_FILE("KF3"),
  FILE_SESSION_IDS_MISSING("KF4"),
  FILE_VERSION_CONFLICT("KF5"),
  FILE_LATEST_VERSION_ERROR("KF6"),
  FILE_GET_DIFFS_ERROR("KF7"),
  FILE_PUT_DIFFS_ERROR("KF8"),
  FILE_TOKEN_ERROR("KF9"),
  FILE_GET_INFO_ERROR("KF10"),
  UNABLE_TO_CHECK_FILE_LOCK("KF11"),
  FILE_DOWNLOAD_ERROR("KF12"),
  FILE_UPLOAD_ERROR("KF13"),
  FILE_IS_SAVE_PENDING("KF14"),
  VIEW_ONLY_SESSION("KF15"),
  NO_EDITING_RIGHTS("KF16"),
  FILE_DOESNT_EXIST("KF17"),
  FILE_GET_DATA_ERROR("KF18"),
  STORAGE_IS_NOT_CONNECTED("KF19"),
  STORAGE_IS_DISABLED("KF20"),
  FILE_DELETED("KF21"),
  FILE_NOT_ACCESSIBLE("KF22"),
  NO_SPACE_LEFT("KF23"),
  GENERAL_KUDO_ERROR("KF24"),
  UNABLE_TO_CREATE_PRESIGNED_URL("KF25"),
  LONG_OBJECT_NAME("KF26");

  private final String code;

  KudoErrorCodes(String code) {
    this.code = code;
  }

  public String getCode() {
    return this.code;
  }
}
