package com.graebert.storage.resources;

public enum KudoResourceErrorCodes {
  INVALID_RESOURCE_TYPE("KR0"),
  INVALID_OBJECT_ID("KR1"),
  OBJECT_CONVERSION_ERROR("KR2"),
  FOLDER_DOES_NOT_EXIST("KR3"),
  OBJECT_NAME_ALREADY_EXIST("KR4"),
  OBJECT_SHARE_ERROR("KR6"),
  OBJECT_UPLOAD_ERROR("KR7"),
  OBJECT_UPDATE_ERROR("KR8"),
  OBJECT_DELETE_ERROR("KR9"),
  OBJECT_DOWNLOAD_ERROR("KR10"),
  OBJECT_CREATE_ERROR("KR11"),
  OBJECT_ACCESS_ERROR("KR12"),
  INVALID_OWNER("KR13"),
  FILE_NOT_SUPPORTED("KR14"),
  CANNOT_CREATE_OBJECT("KR15"),
  OBJECT_DOES_NOT_EXIST("KR16"),
  NOTHING_TO_UPDATE("KR17"),
  CANNOT_UPDATE_OBJECT("KR18"),
  WRONG_OBJECT_TYPE("KR19"),
  INVALID_DOWNLOAD_TOKEN("KR20"),
  NOTHING_TO_DELETE("KR21"),
  INVALID_FONT_DATA("KR22"),
  INVALID_ITEM_OWNER_TYPE("KR23"),
  INVALID_FOLDER_PATH("KR24");

  private final String code;

  KudoResourceErrorCodes(String code) {
    this.code = code;
  }

  public String getCode() {
    return this.code;
  }
}
