package com.graebert.storage.resources;

public enum ResourceErrorIds {
  INVALID_TYPE("RS1"),
  FOLDER_ID_MISSING("RS2"),
  COULD_NOT_PARSE_OBJECT("RS3"),
  FOLDER_NOT_FOUND("RS4"),
  DUPLICATE_NAME("RS5"),
  INVALID_S3_PARAMS("RS6"),
  PUBLIC_SHARING_NOT_ALLOWED("RS7"),
  NO_ACCESS("RS8"),
  NO_PERMISSION_TO_SHARE("RS9"),
  NO_PERMISSION_TO_UNSHARE("RS10"),
  NO_PERMISSION_TO_UPDATE("RS11"),
  NO_PERMISSION_TO_DELETE("RS12"),
  NO_PERMISSION_TO_UPLOAD("RS13"),
  NO_PERMISSION_TO_CREATE_FOLDER("RS14"),
  THIS_FOLDER("RS15"),
  THIS_FILE("RS16"),
  INVALID_OWNER_INFO("RS17"),
  NO_PERMISSION_TO_CREATE_FILE("RS18"),
  FILE_NOT_SUPPORTED_FOR_BLOCKS("RS19"),
  FILE_NOT_SUPPORTED_FOR_TEMPLATES("RS20"),
  FILE_NOT_SUPPORTED_FOR_FONTS("RS21"),
  FILE_NOT_SUPPORTED_FOR_LISPS("RS22"),
  COULD_NOT_CREATE_IN_SHARING_FOLDER("RS23"),
  OBJECT_NOT_FOUND("RS24"),
  NOTHING_TO_UPDATE("RS25"),
  OBJECT_TYPE_NOT_MATCH("RS26"),
  FILE_NOT_FOUND("RS27"),
  INVALID_DOWNLOAD_TOKEN("RS28"),
  NOTHING_TO_DELETE("RS29"),
  COULD_NOT_READ_FONT_FILE("RS30"),
  OWNER_TYPE_NOT_FOUND("RS31"),
  INVALID_PATH_FOR_FOLDER("RS32"),
  COLLABORATORS_NOT_PROVIDED("RS33"),
  COLLABORATOR_NOT_FOUND("RS34"),
  NOTHING_TO_MOVE("RS35"),
  PUBLIC_TO_OTHER_MOVE_RESTRICTED("RS36"),
  CANNOT_MOVE_TO_SAME_FOLDER("RS37");

  public final String id;

  ResourceErrorIds(String id) {
    this.id = id;
  }
}
